---
abstract: 'Custom errorhandling in deployed applications'
author:
  - 'Andreas Marienborg <andremar@cpan.org>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Test: 0
  Catalyst::View: 0
  Catalyst::View::TT: 0
  FindBin: 0
  HTTP::Request::AsCGI: 0
  Test::More: 0.96
  Text::Diff: 0
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Action-RenderView-ErrorHandler
requires:
  Carp: 0
  Catalyst::Action::RenderView: 0
  Catalyst::View::TT: 0
  Class::Inspector: 0
  MRO::Compat: 0
  Moose: 0
  Moose::Role: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/omega/catalyst-action-renderview-errorhandler.git
version: 0.100164
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@ANDREMAR/@Basic/GatherDir'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@ANDREMAR/@Basic/PruneCruft'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@ANDREMAR/@Basic/ManifestSkip'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@ANDREMAR/@Basic/MetaYAML'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::License
      name: '@ANDREMAR/@Basic/License'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@ANDREMAR/@Basic/Readme'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@ANDREMAR/@Basic/ExtraTests'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@ANDREMAR/@Basic/ExecDir'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@ANDREMAR/@Basic/ShareDir'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@ANDREMAR/@Basic/MakeMaker'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@ANDREMAR/@Basic/Manifest'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@ANDREMAR/@Basic/TestRelease'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@ANDREMAR/@Basic/ConfirmRelease'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@ANDREMAR/@Basic/UploadToCPAN'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@ANDREMAR/AutoPrereqs'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@ANDREMAR/PkgVersion'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@ANDREMAR/MetaConfig'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@ANDREMAR/MetaJSON'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@ANDREMAR/NextRelease'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@ANDREMAR/PodSyntaxTests'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@ANDREMAR/Repository'
      version: 0.18
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@ANDREMAR/TestMoreWithSubtests'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@ANDREMAR/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@ANDREMAR/@Git/Check'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@ANDREMAR/@Git/Commit'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@ANDREMAR/@Git/Tag'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@ANDREMAR/@Git/Push'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@ANDREMAR/Git::NextVersion'
      version: 1.112510
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300000
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300000
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300000
